Feature: Sync all border values on sync click
tomusborne/generateblocks pull request #1026
Opened 2023-05-31 21:25 UTC by tomusborne

2023-06-02 15:11 UTC, JeanPaiva requested changes
Found two bugs.

Steps to reproduce the first:

1. Add width values to all 4 borders and remove them.
2. Save the page, and refresh, the sync is now active.

Steps to reproduce the second:

1. Add border width, style, and color, to any side except the TOP side.
2. Enable sync, click on the color field, no color is set.
3. Un-sync, the same occurs only for the top side, all other sides work fine.

2023-06-02 15:28 UTC, tomusborne commented
@JeanPaiva first bug should be fixed. Any ideas on what's going on with the second one? Value looks like it exists, maybe the component just isn't re-rendering?

2023-06-07 11:16 UTC, JeanPaiva commented
@tomusborne I fixed the second issue.

2023-06-07 11:16 UTC, JeanPaiva approved these changes

2023-06-07 14:14 UTC, merged