Query - Fix offset and post per page in preview
tomusborne/generateblocks pull request #1536
Opened 2024-11-25 21:28 UTC by iansvo

Fixes #1448 
Requires: https://github.com/tomusborne/generateblocks-pro/pull/769

2024-11-26 19:40 UTC, tomusborne requested changes

2024-11-26 19:40 UTC, tomusborne commented on src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
> +			console.log( { perPage, offset } );
Need to remove this.

2024-11-26 21:38 UTC, iansvo commented on src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
> +			console.log( { perPage, offset } );
Done.

2024-11-29 16:57 UTC, iansvo commented
@tomusborne As noted on the free PR, I had to make some adjustments to the way the pagination works to properly support non post-type queries. 

I confirmed it works as expected on frontend and in preview with all three query types.

2024-12-03 00:37 UTC, tomusborne commented on includes/blocks/class-query-page-numbers.php
> +			$query_data;
What's this guy doing here?

2024-12-04 14:45 UTC, merged